version: '3'
services:
  apache:
    image: 'php82_ionic'
    container_name: app_web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - '7002:80'
    volumes:
      - ./:/var/www/html
      - ./dockerconf/apache2.conf:/etc/apache2/apache2.conf
      - ./dockerconf/ports.conf:/etc/apache2/ports.conf
      - ./.htaccess:/var/www/html/.htaccess
