version: '3'
services:
  laravel.test:
    image: 'php82'
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - '7000:80'
    volumes:
      - ./:/var/www/html
      - ./dockerconf/apache2.conf:/etc/apache2/apache2.conf
      - ./dockerconf/ports.conf:/etc/apache2/ports.conf

